version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 127.0.0.0.1:9090:9090
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  grafana_init:
    entrypoint: "/opt/init.sh"
    depends_on:
      - grafana
    image: grafana/grafana:latest
    volumes:
      - ./init.sh:/opt/init.sh
  coinmarketcap-exporter:
    environment:
      - COINMARKETCAP_API_KEY=$COINMARKETCAP_API_KEY
    image: coinmarketcap-exporter:latest

